### ISSUE TITLE
Undefined variables in plotting

### ISSUE THREAD

**Issue by trevor-moon** [AppleMan05/python-network-monitor#3]
Here is the terminal output:

![image](https://user-images.githubusercontent.com/29641134/137439053-d8a8af91-6457-4646-97dd-e6ca23f2b4f1.png)

Here is the issue:

![image](https://user-images.githubusercontent.com/29641134/137439176-61fd53a0-b0a1-41f2-843a-15c8681aad57.png)

**Comment by CosmicRaptor** [comment]
Oh god i had that line for testing and forgot to remove it. I'll fix it right now

**Comment by CosmicRaptor** [comment]
Resolved.
